version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
#      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
#      KAFKA_ADVERTISED_LISTENERS: INTERNAL://:9092,EXTERNAL://:9093
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
#    depends_on:
#      - zookeeper

#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    ports:
#      - "9000:8080"
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=yetao
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=192.168.123.123:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=192.168.123.123:2181
#    depends_on:
#      - kafka
#      - zookeeper


#  kafka-manager:
#    image: kafkamanager/kafka-manager
#    ports:
#      - "9000:9000"
#    environment:
#      ZK_HOSTS: zookeeper:2181

#  kafka-ui:
#    image: provectuslabs/kafka-ui
#    container_name: kafka-ui
#    ports:
#      - "8082:8080"
#    restart: always
#    environment:
#      - KAFKA_CLUSTERS_0_NAME=yetao
#      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
#      - KAFKA_CLUSTERS_0_ZOOKEEPER=zookeeper:2181
#    #      - KAFKA_CLUSTERS_0_READONLY=false
#    depends_on:
#      - kafka
#      - zookeeper